#!/bin/bash
#SBATCH --job-name="order"
#SBATCH --partition=main
#SBATCH --time=05:00:00
#SBATCH --cpus-per-task=2
#SBATCH --mem=6G
#SBATCH --array=0-49
#SBATCH --output=./slurm_output/slurm-%A_%a.out
#SBATCH --requeue

MY_ARG=$1

module load any/python/3.9.9
source /gpfs/space/home/troosma/bakatoo/bakatoo/baka_env/bin/activate
python3 --version
which python3

srun python ./scripts/hpc/sin_distributed_uneven.py --seed $SLURM_ARRAY_TASK_ID --multiplier $MY_ARG -o './andmed/sin_order'
